spring.datasource.url=jdbc:postgresql://localhost:5432/stayhub_db
spring.datasource.username=postgres
spring.datasource.password=stayhub123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Giới hạn dung lượng upload ảnh công tơ, hóa đơn, CCCD
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080

# --- BỔ SUNG CẤU HÌNH JWT BẢO MẬT CHÈN VÀO ĐÂY ---
jwt.secret=3c9a6a6f7b4845345272654d61737465725365637265744b6579323032365374617948